spring:
  config:
    location: http://localhost:8070
  application:
    name: api-gateway
  profiles:
    active: dev
springdoc:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTION
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "gateway, api-docs, swagger-ui"
#  endpoint:
#    health:
#      probes:
#        enabled: true
server:
  port: 8060



logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG