version: '3'
services:
  mongodb_orders:
    image: mongo
    container_name: mongodb_orders
    ports:
      - "28084:27017"
    environment:
      MONGO_INITDB_DATABASE: order
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: wanderSecret
      MONGO_INITDB_ROOT_AUTH_SOURCE: admin
    volumes:
      - mongodb_orders_data:/data/db

  mongodb_cars:
    image: mongo
    container_name: mongodb_cars
    ports:
      - "28085:27017"
    environment:
      MONGO_INITDB_DATABASE: car
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: wanderSecret
      MONGO_INITDB_ROOT_AUTH_SOURCE: admin
    volumes:
      - mongodb_cars_data:/data/db

    networks:
      - rent-a-car-net

  userDB:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'User'
      MYSQL_PASSWORD: 'wanderSecret'
      MYSQL_ROOT_PASSWORD: 'wanderSecret'
    ports:
      - '3306:3306'
    expose:
      - '3306'

  configuration-service:
    image: configuration-service:latest
    build: ../configuration-service/.
    ports:
      - "8071:8071"
    container_name: configuration-service
    networks:
      - rent-a-car-net


  discovery-service:
    image: discovery-service:latest
    build: ../discovery-service/.
    ports:
      - "8070:8070"
    depends_on:
      - configuration-service
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8070"
      SPRING_CLOUD_CONFIG_URI: "http://configuration-service:8071"
#      CONFIGSERVER_PORT: "8071"
    container_name: discovery-service
    networks:
      - rent-a-car-net


  authentication-service:
    image: authentication-service:latest
    build: ../authentication-service/.
    container_name: authentication-service
    ports:
      - "8185:8185"

    depends_on:
      - discovery-service
      - mongodb_orders
      - mongodb_cars
      - userDB
      - configuration-service
    networks:
      - rent-a-car-net
  api-gateway:
    image: api-gateway:latest
    build: ../api-gateway/.
    container_name: api-gateway-service
    environment:
      PROFILE: "dev"
      SERVER_PORT: "8060"
      SPRING_CLOUD_CONFIG_URI: "http://configuration-service:8071"
      SPRING_CLOUD_CONFIG_PORT: "8071"
    ports:
      - "8060:8060"
    depends_on:
      - discovery-service
      - configuration-service
    networks:
      - rent-a-car-net
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
     - rent-a-car-net
    container_name: rabbitmq
networks:
  rent-a-car-net:
    driver: bridge
volumes:
  mongodb_orders_data:
  mongodb_cars_data:


